In [12]:
import numpy as np

In [13]:
X = np.array([
    [0.2029, 0.6136, 0.899,  0.6665],
    [0.0,    0.3943, 0.3636, 0.7103],
    [0.2174, 0.7781, 0.6869, 1.0],
    [0.3123, 0.893,  0.5051, 0.6404],
    [0.635,  0.0,    0.5404, 0.9743],
    [1.0,    0.1932, 1.0,    0.3266],
    [0.0081, 1.0,    0.0,    0.0],
    [0.031,  0.6188, 0.3737, 0.4194],
    [0.4,    0.2245, 0.6566, 0.0674],
    [0.3249, 0.1123, 0.4848, 0.5744]
])

y = np.array([[1],[1],[0],[1],[0],[0],[1],[1],[0],[1]])

In [14]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)


In [15]:
np.random.seed(1)

input_size = 4
hidden_size = 5
output_size = 1

W1 = np.random.rand(input_size, hidden_size)
b1 = np.random.rand(hidden_size)

W2 = np.random.rand(hidden_size, output_size)
b2 = np.random.rand(output_size)

learning_rate = 0.1


In [16]:
W1

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
        1.46755891e-01],
       [9.23385948e-02, 1.86260211e-01, 3.45560727e-01, 3.96767474e-01,
        5.38816734e-01],
       [4.19194514e-01, 6.85219500e-01, 2.04452250e-01, 8.78117436e-01,
        2.73875932e-02],
       [6.70467510e-01, 4.17304802e-01, 5.58689828e-01, 1.40386939e-01,
        1.98101489e-01]])

In [17]:
b1

array([0.80074457, 0.96826158, 0.31342418, 0.69232262, 0.87638915])

In [18]:
W2

array([[0.89460666],
       [0.08504421],
       [0.03905478],
       [0.16983042],
       [0.8781425 ]])

In [19]:
b2

array([0.09834683])

In [20]:
def forward_pass(x):
    # Hidden layer
    z1 = np.dot(x, W1) + b1
    a1 = sigmoid(z1)

    # Output layer
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    return a1, a2

In [21]:
def backpropagation(x, y_true, a1, y_pred):
    global W1, W2, b1, b2

    # Output layer error
    error = y_true - y_pred
    delta_output = error * sigmoid_derivative(y_pred)

    # Hidden layer error
    delta_hidden = delta_output.dot(W2.T) * sigmoid_derivative(a1)

    # Weight updates
    W2 += a1.reshape(-1,1) * delta_output * learning_rate
    b2 += delta_output * learning_rate

    W1 += x.reshape(-1,1) @ delta_hidden.reshape(1,-1) * learning_rate
    b1 += delta_hidden * learning_rate


In [23]:
epochs = 1000

for epoch in range(epochs):
    for i in range(len(X)):
        a1, y_pred = forward_pass(X[i])
        backpropagation(X[i], y[i], a1, y_pred)

    if epoch % 200 == 0:
        loss = np.mean((y - y_pred)**2)
        print(f"Epoch {epoch}, Loss: {loss}")


Epoch 0, Loss: 0.24360201884130167
Epoch 200, Loss: 0.24122871778953744
Epoch 400, Loss: 0.24017051390395952
Epoch 600, Loss: 0.24006164537121402
Epoch 800, Loss: 0.24088079097435325


In [11]:
x_sample = X[0]
y_sample = y[0]

a1, output = forward_pass(x_sample)

error = y_sample - output
gradient_output = error * sigmoid_derivative(output)

print("Predicted Output:", output)
print("Gradient at Output Node:", gradient_output)


Predicted Output: [0.66484558]
Gradient at Output Node: [0.0746811]
